### ISSUE TITLE
Tip dates functionality?

### ISSUE THREAD

**Issue by ksw9** [richelbilderbeek/beastier#18]
Great resource! Do you have plans for a function to import tip dates?
Thank you!

**Comment by richelbilderbeek** [comment]
Moved Issue to [a babette Issue](https://github.com/richelbilderbeek/babette/issues/27).

Spoiler, @ksw9: 

> If I have a user with a use case: definitely! Could I use you for this? 

Close this Issue as it is moved to a more appropriate place.
